### ISSUE TITLE
Create contact us form component

### ISSUE THREAD

**Issue by MadhushaPrasad** [ms-club-sliit/fcmu#13]

**Comment by IndudiniThennakoon** [comment]
Can I assign for this issue

**Comment by MadhushaPrasad** [comment]
yah sure, you can get all information in figma file

**Comment by MadhushaPrasad** [comment]
![image](https://user-images.githubusercontent.com/50085447/222877051-bfa7cba3-b411-4360-b4b1-a1165ffe7a2f.png)

**Comment by MadhushaPrasad** [comment]
@IndudiniThennakoon  I am going to assign this issue for you.

- [ ] use functional component
- [ ] create as a separate component in components folder
- [ ]  you can get CSS styles from figma file
- [ ] use global CSS variables when you are going to give colors for elements

**Comment by MadhushaPrasad** [comment]
please give an update on this issue immediately

**Comment by IndudiniThennakoon** [comment]
I think this issue has already completed, u can close the issue.

PR:  Contact us form done #40 

> please give an update on this issue immediately
