### ISSUE TITLE
About us "Who We Are" Section

### ISSUE THREAD

**Issue by MadhushaPrasad** [ms-club-sliit/fcmu#25]

**Comment by MadhushaPrasad** [comment]
@AkilaNPerera I will assign you for this issue, if you got any issues, You can ask it in the comment section or discussions section.

**Comment by MadhushaPrasad** [comment]
@AkilaNPerera give me some update on this issue

**Comment by shafdo** [comment]
@MadhushaPrasad I made a PR for this issue. Please check it out
