### ISSUE TITLE
Create event page hero section

### ISSUE THREAD

**Issue by MadhushaPrasad** [ms-club-sliit/fcmu#29]
![image](https://user-images.githubusercontent.com/50085447/225854789-51a20a5b-4931-4033-9d55-efd33f2b8a1d.png)

**Comment by Navojith** [comment]
can I do this?

**Comment by Navojith** [comment]
can i do this?

**Comment by Navojith** [comment]
I will do this

**Comment by Navojith** [comment]
This has already been completed and merged. You can close this issue

**Comment by MadhushaPrasad** [comment]
> This has already been completed and merged. You can close this issue

sure malli
