### ISSUE TITLE
Create landing page who we are section

### ISSUE THREAD

**Issue by MadhushaPrasad** [ms-club-sliit/fcmu#4]
![whoWeAre](https://user-images.githubusercontent.com/50085447/219942896-12813de9-17e6-4a2b-8ae3-1766c0939f00.PNG)

please create the landing page who we are section with responsive for all devices

**Comment by Navojith** [comment]
Is there a media unit board of officials img already or should I use a dummy img?

**Comment by MadhushaPrasad** [comment]
> Is there a media unit board of officials img already or should I use a dummy img?

you can get this board img from their FB page

**Comment by MadhushaPrasad** [comment]
@Navojith now you can do this issue bro
