### ISSUE TITLE
Create footer

### ISSUE THREAD

**Issue by MadhushaPrasad** [ms-club-sliit/fcmu#8]
![image](https://user-images.githubusercontent.com/50085447/219943467-1fecdec7-bce2-4144-8514-479e4aeab9f8.png)

please create the landing page footer with responsive for all devices

**Comment by MadhushaPrasad** [comment]
this is the new design of footer section, you have to implement this one

![image](https://user-images.githubusercontent.com/50085447/224526001-a0aae977-964b-4d8b-a203-eca565f95e1e.png)

**Comment by MadhushaPrasad** [comment]
@Kesh17

**Comment by uihalagedara** [comment]
@MadhushaPrasad Spellings should be correct in the "subscribe". In the design it says "Subcribe"

**Comment by MadhushaPrasad** [comment]
> @MadhushaPrasad Spellings should be correct in the "subscribe". In the design it says "Subcribe"

ok i will update it

**Comment by MadhushaPrasad** [comment]
@Kesh17 give me some update on this issue

**Comment by KeshalaHapuarachchi** [comment]
@MadhushaPrasad @uihalagedara  It is finish. But there are several changes. I will fix them now. 

![update 1](https://user-images.githubusercontent.com/105196447/231119445-8af6a552-a76a-4628-b681-4308b7683633.PNG)

**Comment by MadhushaPrasad** [comment]
please check the figma design and fix just like that, need to be adjust some elements like this
![image](https://user-images.githubusercontent.com/50085447/232179900-f5691953-de38-40da-acc6-8d08a25e83b2.png)

**Comment by KeshalaHapuarachchi** [comment]
![Footer ex](https://user-images.githubusercontent.com/105196447/234769339-06b17252-1b2e-4d67-a554-d607ac218f97.PNG)

**Comment by uihalagedara** [comment]
Upload the mobile view also
